### ISSUE TITLE
关于README文件的两个问题

### ISSUE THREAD

**Issue by Baka632** [dscmarkw/aneot#61]
1. 标题

> Another End of Terra **_（AnEot)_**

左边的括号是全角括号，右边的却是半角括号，看上去非常不协调。

2. 标题下面对《回归线》的介绍
> **_An_** fanmade literary journal based on mobile game *Arknights*.

"fanmade" 前面应该加"a"而非"an"

以上

**Comment by yige-yigeren** [comment]
草
